// This file was generated by PermissionsDispatcher. Do not modify!
package com.netease.nim.demo.main.activity;

import android.support.v4.app.ActivityCompat;

import permissions.dispatcher.PermissionUtils;

final class ContactListActivityPermissionsDispatcher {
  private static final int REQUEST_SHOWCONTACTS = 0;

  private static final String[] PERMISSION_SHOWCONTACTS = new String[] {"android.permission.READ_CONTACTS"};

  private ContactListActivityPermissionsDispatcher() {
  }

  static void showContactsWithPermissionCheck(ContactListActivity target) {
    if (PermissionUtils.hasSelfPermissions(target, PERMISSION_SHOWCONTACTS)) {
      target.showContacts();
    } else {
      ActivityCompat.requestPermissions(target, PERMISSION_SHOWCONTACTS, REQUEST_SHOWCONTACTS);
    }
  }

  static void onRequestPermissionsResult(ContactListActivity target, int requestCode,
                                         int[] grantResults) {
    switch (requestCode) {
      case REQUEST_SHOWCONTACTS:
      if (PermissionUtils.verifyPermissions(grantResults)) {
        target.showContacts();
      } else {
        target.doReadContactSPermissionDenied();
      }
      break;
      default:
      break;
    }
  }
}
