// This file was generated by PermissionsDispatcher. Do not modify!
package com.netease.nim.demo.main.activity;

import android.support.v4.app.ActivityCompat;

import permissions.dispatcher.PermissionUtils;

final class CustomScanActivityPermissionsDispatcher {
  private static final int REQUEST_OPENCAMERA = 1;

  private static final String[] PERMISSION_OPENCAMERA = new String[] {"android.permission.CAMERA"};

  private CustomScanActivityPermissionsDispatcher() {
  }

  static void openCameraWithPermissionCheck(CustomScanActivity target) {
    if (PermissionUtils.hasSelfPermissions(target, PERMISSION_OPENCAMERA)) {
      target.openCamera();
    } else {
      ActivityCompat.requestPermissions(target, PERMISSION_OPENCAMERA, REQUEST_OPENCAMERA);
    }
  }

  static void onRequestPermissionsResult(CustomScanActivity target, int requestCode,
                                         int[] grantResults) {
    switch (requestCode) {
      case REQUEST_OPENCAMERA:
      if (PermissionUtils.verifyPermissions(grantResults)) {
        target.openCamera();
      } else {
        target.donotopenCamera();
      }
      break;
      default:
      break;
    }
  }
}
